### ISSUE TITLE
single GPU inference error

### ISSUE THREAD

**Issue by hellozgm** [YudeWang/deeplabv3plus-pytorch#33]
hi，我用你原来的多GPU的train.py训练代码训练好的模型，我想用单块GPU做inference，修改好cfg.TEST_GPUS=1，去掉了多个代码中的*.to(1)这种情况，然后运行test.py但是会报错呢，报错内容如下，请问这是啥原因呢，感谢~
```
Traceback (most recent call last):
  File "test.py", line 94, in <module>
    test_net()
  File "test.py", line 42, in test_net
    net.load_state_dict(model_dict)
  File "/home/mypc/lib/anaconda2/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for deeplabv3plus:
	Missing key(s) in state_dict: "aspp.branch1.0.weight", "aspp.branch1.0.bias", "aspp.branch1.1.weight", "aspp.branch1.1.bias", "aspp.branch1.1.running_mean", "aspp.branch1.1.running_var", "aspp.branch2.0.weight", "aspp.branch2.0.bias", "aspp.branch2.1.weight", "aspp.branch2.1.bias", "aspp.branch2.1.running_mean", "aspp.branch2.1.running_var", "aspp.branch3.0.weight", "aspp.branch3.0.bias", "aspp.branch3.1.weight", "aspp.branch3.1.bias"........................
```

**Comment by YudeWang** [comment]
@hellozgm 
你加载错模型参数了

**Comment by hellozgm** [comment]
> @hellozgm
> 你加载错模型参数了

但是为啥同样的模型，我用2块GPU做inference的时候是好的呀。。

**Comment by YudeWang** [comment]
@hellozgm 
多卡训练使用了nn.DataParallel对网络进行嵌套，保存参数时候key字段应该是module.aspp.branch1.0.weight这个样子。如果没有用nn.DataParallel那字段应该才是aspp.branch1.0.weight。你做单卡inference时候我不知道你改了什么地方，如果修改了nn.DataParallel就要注意参数加载对应。
我程序很多地方写的不完善，经常只修改config.py是不够的，还得用的时候debug一下：）

**Comment by hellozgm** [comment]
Slove this problem by modify test.py code:
1. add  `net = nn.DataParallel(net)` although using 1 single GPU
2. modify all `*.to(1)`  to  `*.to(device)`
