### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

### ISSUE THREAD

**Issue by zdaiot** [YudeWang/deeplabv3plus-pytorch#34]
Hello, when I use the code `self.unet = DeepLabV3Plus(model_backbone='res50_atrous', num_classes=self.output_ch)` to  invoke a model, some error happen:
```
Train Loss: 0.0088223, lr: params_group_0: 0.000200000000, : 100%|██████████████████████████████████████████████████████████████████████████████████████▉| 1067/1068 [17:38<00:00,  1.02it/s]Traceback (most recent call last):
  File "train_sfold.py", line 194, in <module>
    main(config)
  File "train_sfold.py", line 79, in main
    solver.train(index)
  File "/mnt/Data/mxq/project/Kaggle-Pneumothorax-Seg/solver.py", line 192, in train
    net_output = self.unet(images)
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Data/mxq/project/Kaggle-Pneumothorax-Seg/models/deeplabv3/deeplabv3plus.py", line 67, in forward
    feature_aspp = self.aspp(layers[-1])
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Data/mxq/project/Kaggle-Pneumothorax-Seg/models/deeplabv3/ASPP.py", line 57, in forward
    global_feature = self.branch5_bn(global_feature)
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Data/mxq/project/Kaggle-Pneumothorax-Seg/models/deeplabv3/sync_batchnorm/batchnorm.py", line 53, in forward
    self.training, self.momentum, self.eps)
  File "/home/lab3/anaconda3/envs/mxq/lib/python3.5/site-packages/torch/nn/functional.py", line 1693, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])
```
my input image size is [8, 3, 768, 768]

**Comment by Liuzhizhiooo** [comment]
how do you solve it?
By remove the batchnorm layer?
